### Get all Quotes
GET http://localhost:8080/api/quote

### Create Quote
POST http://localhost:8080/api/quote
Content-Type: application/json

{
  "@type": "AddQuote",
  "lines": [
    {
      "order": 1,
      "name": "Kratos",
      "text": "Don't be sorry, be better."
    }
  ]
}

### Share Quote
POST http://localhost:8080/api/quote/9fb2cbf6-0171-4a94-84b8-ef1506cd7c6f
Content-Type: application/json

{
  "@type": "ShareQuote",
  "id": {
    "value": "9fb2cbf6-0171-4a94-84b8-ef1506cd7c6f"
  }
}