### Get all Quotes
GET http://localhost:8080/api/quote

### Create Quote
POST http://localhost:8080/api/quote
Content-Type: application/json

{
  "@type": "AddQuote",
  "lines": [
    {
      "order": 1,
      "name": "Snarf",
      "text": "snarf snarf"
    },
    {
      "order": 2,
      "name": "Lion-O",
      "text": "stfu snarf"
    }
  ]
}