CREATE TABLE "quote"
(
    ID VARCHAR(36) NOT NULL PRIMARY KEY
);

CREATE TABLE "quote_lines"
(
    QUOTE VARCHAR(36) NOT NULL,
    "order" INT,
    NAME VARCHAR NOT NULL,
    TEXT VARCHAR NOT NULL
);

