CREATE TABLE "quote"
(
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    AT TIMESTAMP NOT NULL
);

CREATE TABLE "quote_lines"
(
    QUOTE VARCHAR(36) NOT NULL,
    "order" INT NOT NULL,
    NAME VARCHAR NOT NULL,
    TEXT VARCHAR NOT NULL
);

